### ISSUE TITLE
Using via esm leads to acorn import error

### ISSUE THREAD

**Issue by daKmoR** [xtuc/acorn-import-assertions#11]
## Error
In "real" esm you get this error message

```
import _acorn from "acorn";
       ^^^^^^
SyntaxError: The requested module 'acorn' does not provide an export named 'default'
```

which is true as `acorn` only has named exports
```js
// node_modules/acorn/dist/acorn.mjs
export { Node, Parser, Position, SourceLocation, TokContext, Token, TokenType, defaultOptions, getLineInfo, isIdentifierChar, isIdentifierStart, isNewLine, keywords$1 as keywordTypes, lineBreak, lineBreakG, nonASCIIwhitespace, parse, parseExpressionAt, types$1 as tokContexts, types as tokTypes, tokenizer, version };
```

I assume it keeps working with cjs as it's always an object by default.

## Reproduction
I created a reproduction here
https://github.com/daKmoR/acorn-import-assertions-esm-bug

```
git clone https://github.com/daKmoR/acorn-import-assertions-esm-bug.git
cd acorn-import-assertions-esm-bug
npm i
npm run build
```

## Suggestion

it can probably be solved via

```diff
- import _acorn from "acorn";
+ import * as _acorn from "acorn";
```

in https://github.com/xtuc/acorn-import-assertions/blob/main/src/index.js#L1

**Comment by xtuc** [comment]
Fixed in https://github.com/xtuc/acorn-import-assertions/commit/08ab26b9e2a5bca28f374a8a3e17f0c8c74b8ad0

**Comment by daKmoR** [comment]
thxxxx 🙇‍♂️
