### ISSUE TITLE
Build with babel-plugin-transform-charcodes

### ISSUE THREAD

**Issue by xtuc** [xtuc/acorn-import-assertions#9]
https://github.com/xtuc/acorn-import-assertions/commit/5f4e8146ea79478435463cd145b99f1322545ffa introduced charcodes package. To avoid distributing the code / optimising we can run https://github.com/xtuc/charcodes/tree/master/packages/babel-plugin-transform-charcodes to transpile them away.

**Comment by alexander-akait** [comment]
Simple solutions

**Comment by xtuc** [comment]
Yeah indeed. I'm planning to do the change, otherwise woudl you mind sending a PR?

**Comment by alexander-akait** [comment]
Right now busy so feel free to do it and we return import assertion in webpack :star:
